### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by Career200** [sitek94/vite-deploy-demo#1]
Deploy workflow does not trigger for some reason.

![image](https://user-images.githubusercontent.com/105638831/219023834-80ffd45c-0faa-4a66-a370-1f38a05eb2f5.png)
![image](https://user-images.githubusercontent.com/105638831/219023693-8cbd4eb0-4599-4be7-91ea-0a62adc6cb48.png)

I found [this solution](https://github.com/orgs/community/discussions/26945) not to work, but `if: always()` instead of `if: always() && (github.ref == 'refs/heads/main')` works fine

**Comment by satr14washere** [comment]
I have the same issue, @Career404 can you send me the fixed workflow file

**Comment by Career200** [comment]
Away from PC, but @SX-9 
you can use [this file](https://github.com/Career404/FCCFront/blob/master/.github/workflows/deploy.yml)

**Comment by sitek94** [comment]
Hey @SX-9 and @Career404,

It seems that it doesn't work for you because your default branch is called `master` instead of `main`. `github.ref == 'refs/heads/main'` ensures that "Deploy" job will only run on push to the `main` branch. 

To fix it you can either [rename your default branch](https://github.com/github/renaming) to `main` or replace every occurrence of `main` branch with `master` in `deploy.yml`.

When it comes to `if: always()` I wouldn't do that, because it basically means that "Deploy" job will run even if "Build" job fails. See [this example](https://github.com/github/renaming) for detailed explanation.

I hope it makes sense :)

**Comment by Career200** [comment]
@sitek94 Thanks a lot for the detailed explanation! I'm blind probably, because I changed the first occurrence of "main" to "master", but not the second one...
